version: '2'
services:
  mysql:
    build: ./mysql
    container_name: mysql-exo2
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    container_name: php-exo2
    ports:
      - '8085:80'
    volumes:
      - ./html:/var/www/html
    links:
      - mysql
volumes:
  db: